"""
Targeted Test Suite — Pattern-Based Type Error Detection

Source: protocol-default-mixed-dataclass-transform.py
Patterns detected: 3
    - inheritance_override (4 tests)
  - decorator_signature (1 tests)
  - protocol_conformance (9 tests)
Test cases generated: 14
"""

# --- Original source ---

from typing import Protocol, TypeVar, Callable, dataclass_transform, Any
from dataclasses import dataclass, field

T = TypeVar("T")

class BaseProcessor(Protocol):
    data_source: str # This field will be generated by dataclass_transform

    def process(self, item: Any) -> str:
        """Processes an item, with a default implementation."""
        return f"Default processing of {item} from {self.data_source}"

    def post_process(self, result: str, finalize: bool = False) -> str:
        """Post-processes results."""
        if finalize:
            return result.upper()
        return result

@dataclass_transform(kw_only_default=True)
def processor_factory[T: type](*, enhance_process: bool = False) -> Callable[[T], T]:
    def wrapper(cls: T) -> T:
        if enhance_process:
            # Dynamically replace a method that has a default in the protocol
            original_process = getattr(cls, 'process', None)
            def enhanced_process(self, item: Any) -> str:
                res = original_process(self, item) if original_process else super(cls, self).process(item) # type: ignore
                return f"Enhanced: {res}"
            cls.process = enhanced_process # type: ignore
        return dataclass(frozen=False)(cls)
    return wrapper

@processor_factory(enhance_process=True)
class MyDataProcessor(BaseProcessor):
    data_source: str = "internal-db" # Overrides default init behavior for dataclass
    config_param: int = 10

    # No explicit 'process' method, should get from protocol or enhanced version.
    # No explicit 'post_process' method, should get from protocol.

class AnotherProcessor(BaseProcessor):
    # Not decorated, must implement or rely on defaults + dataclass logic.
    # If not dataclass_transform, `data_source` won't be an __init__ param.
    def __init__(self, data_source: str, config_param: int):
        self.data_source = data_source
        self.config_param = config_param

    def process(self, item: Any) -> str:
        return f"Another processed {item} from {self.data_source} with config {self.config_param}"

if __name__ == "__main__":
    processor1 = MyDataProcessor(config_param=5) # 'data_source' has a default
    print(processor1.process("data_A"))
    print(processor1.post_process("processed_A", finalize=True))
    # reveal_type(processor1.process)
    # reveal_type(processor1.data_source)

    processor2 = AnotherProcessor(data_source="external-api", config_param=20)
    print(processor2.process("data_B"))
    print(processor2.post_process("processed_B"))
    # Type checkers might disagree on:
    # 1. Whether MyDataProcessor correctly implements BaseProcessor (dataclass_transform vs Protocol defaults).
    # 2. The constructor signature of MyDataProcessor.
    # 3. The actual callable used for 'process' (decorated, protocol default, or inherited).

# --- Test infrastructure ---
BUGS = []
_SOURCE_LINE_OFFSET = 13

# --- Test cases ---

def test_AnotherProcessor_process_via_base_ref():
    """Call AnotherProcessor.process through a BaseProcessor reference."""
    try:
        obj: BaseProcessor = AnotherProcessor()
        result = obj.process()
    except (TypeError, ValueError, AttributeError, KeyError) as e:
        BUGS.append({"line": 47, "type": type(e).__name__, "error": str(e)[:200], "test": "override_via_base"})


def test_AnotherProcessor_process_direct():
    """Call AnotherProcessor.process directly."""
    try:
        obj = AnotherProcessor()
        result = obj.process()
    except (TypeError, ValueError, AttributeError, KeyError) as e:
        BUGS.append({"line": 47, "type": type(e).__name__, "error": str(e)[:200], "test": "override_direct"})


def test_AnotherProcessor_isinstance_BaseProcessor():
    """Verify AnotherProcessor is an instance of BaseProcessor."""
    try:
        obj = AnotherProcessor()
        if not isinstance(obj, BaseProcessor):
            BUGS.append({"line": 47, "type": "InheritanceError", "error": "AnotherProcessor is not instance of BaseProcessor", "test": "isinstance_check"})
    except (TypeError, ValueError, AttributeError, KeyError) as e:
        BUGS.append({"line": 47, "type": type(e).__name__, "error": str(e)[:200], "test": "isinstance_check"})


def test_AnotherProcessor_super_process():
    """Verify super().process() works from AnotherProcessor."""
    try:
        obj = AnotherProcessor()
        base_method = getattr(super(type(obj), obj), "process", None)
        if base_method is not None:
            result = base_method()
    except (TypeError, ValueError, AttributeError, KeyError) as e:
        BUGS.append({"line": 47, "type": type(e).__name__, "error": str(e)[:200], "test": "super_call"})


def test_processor_factory_decorated_callable():
    """Verify decorated function processor_factory is callable."""
    if not callable(processor_factory):
        BUGS.append({"line": 20, "type": "TypeError", "error": "processor_factory is not callable after decoration", "test": "decorated_callable"})


def test_MyDataProcessor_has_post_process():
    """Verify MyDataProcessor has required protocol method 'post_process'."""
    try:
        obj = MyDataProcessor()
        method = getattr(obj, "post_process", None)
        if method is None:
            BUGS.append({"line": 6, "type": "AttributeError", "error": "MyDataProcessor missing protocol method post_process", "test": "protocol_method_exists"})
        elif not callable(method):
            BUGS.append({"line": 6, "type": "TypeError", "error": "MyDataProcessor.post_process is not callable", "test": "protocol_method_callable"})
    except (TypeError, ValueError, AttributeError, KeyError) as e:
        BUGS.append({"line": 6, "type": type(e).__name__, "error": str(e)[:200], "test": "protocol_check"})


def test_MyDataProcessor_has_data_source():
    """Verify MyDataProcessor has required protocol method 'data_source'."""
    try:
        obj = MyDataProcessor()
        method = getattr(obj, "data_source", None)
        if method is None:
            BUGS.append({"line": 6, "type": "AttributeError", "error": "MyDataProcessor missing protocol method data_source", "test": "protocol_method_exists"})
        elif not callable(method):
            BUGS.append({"line": 6, "type": "TypeError", "error": "MyDataProcessor.data_source is not callable", "test": "protocol_method_callable"})
    except (TypeError, ValueError, AttributeError, KeyError) as e:
        BUGS.append({"line": 6, "type": type(e).__name__, "error": str(e)[:200], "test": "protocol_check"})


def test_MyDataProcessor_has_process():
    """Verify MyDataProcessor has required protocol method 'process'."""
    try:
        obj = MyDataProcessor()
        method = getattr(obj, "process", None)
        if method is None:
            BUGS.append({"line": 6, "type": "AttributeError", "error": "MyDataProcessor missing protocol method process", "test": "protocol_method_exists"})
        elif not callable(method):
            BUGS.append({"line": 6, "type": "TypeError", "error": "MyDataProcessor.process is not callable", "test": "protocol_method_callable"})
    except (TypeError, ValueError, AttributeError, KeyError) as e:
        BUGS.append({"line": 6, "type": type(e).__name__, "error": str(e)[:200], "test": "protocol_check"})


def test_BaseProcessor_non_conforming_object():
    """Pass a non-conforming object where Protocol BaseProcessor is expected."""
    class _FakeNonConforming:
        pass
    fake = _FakeNonConforming()
    for func_name_check, func_obj in [(k, v) for k, v in globals().items() if callable(v)]:
        pass


def test_MyDataProcessor_non_conforming_object():
    """Pass a non-conforming object where Protocol MyDataProcessor is expected."""
    class _FakeNonConforming:
        pass
    fake = _FakeNonConforming()
    for func_name_check, func_obj in [(k, v) for k, v in globals().items() if callable(v)]:
        pass


def test_MyDataProcessor_has_post_process():
    """Verify MyDataProcessor has required protocol method 'post_process'."""
    try:
        obj = MyDataProcessor()
        method = getattr(obj, "post_process", None)
        if method is None:
            BUGS.append({"line": 40, "type": "AttributeError", "error": "MyDataProcessor missing protocol method post_process", "test": "protocol_method_exists"})
        elif not callable(method):
            BUGS.append({"line": 40, "type": "TypeError", "error": "MyDataProcessor.post_process is not callable", "test": "protocol_method_callable"})
    except (TypeError, ValueError, AttributeError, KeyError) as e:
        BUGS.append({"line": 40, "type": type(e).__name__, "error": str(e)[:200], "test": "protocol_check"})


def test_MyDataProcessor_has_data_source():
    """Verify MyDataProcessor has required protocol method 'data_source'."""
    try:
        obj = MyDataProcessor()
        method = getattr(obj, "data_source", None)
        if method is None:
            BUGS.append({"line": 40, "type": "AttributeError", "error": "MyDataProcessor missing protocol method data_source", "test": "protocol_method_exists"})
        elif not callable(method):
            BUGS.append({"line": 40, "type": "TypeError", "error": "MyDataProcessor.data_source is not callable", "test": "protocol_method_callable"})
    except (TypeError, ValueError, AttributeError, KeyError) as e:
        BUGS.append({"line": 40, "type": type(e).__name__, "error": str(e)[:200], "test": "protocol_check"})


def test_MyDataProcessor_has_process():
    """Verify MyDataProcessor has required protocol method 'process'."""
    try:
        obj = MyDataProcessor()
        method = getattr(obj, "process", None)
        if method is None:
            BUGS.append({"line": 40, "type": "AttributeError", "error": "MyDataProcessor missing protocol method process", "test": "protocol_method_exists"})
        elif not callable(method):
            BUGS.append({"line": 40, "type": "TypeError", "error": "MyDataProcessor.process is not callable", "test": "protocol_method_callable"})
    except (TypeError, ValueError, AttributeError, KeyError) as e:
        BUGS.append({"line": 40, "type": type(e).__name__, "error": str(e)[:200], "test": "protocol_check"})


def test_AnotherProcessor_non_conforming_object():
    """Pass a non-conforming object where Protocol AnotherProcessor is expected."""
    class _FakeNonConforming:
        pass
    fake = _FakeNonConforming()
    for func_name_check, func_obj in [(k, v) for k, v in globals().items() if callable(v)]:
        pass


# --- Runner ---
if __name__ == "__main__":
    import sys
    _test_fns = [(name, fn) for name, fn in list(globals().items()) if name.startswith("test_") and callable(fn)]
    print(f"Running {len(_test_fns)} targeted tests...")
    _passed = 0
    _failed = 0
    for _name, _fn in _test_fns:
        try:
            _fn()
            _passed += 1
        except Exception as _e:
            _failed += 1
    print(f"Passed: {_passed}, Failed: {_failed}, Bugs found: {len(BUGS)}")
    for _bug in BUGS:
        print(f"  BUG L{_bug['line']} [{_bug['type']}] {_bug['error']}")
