from typing import Protocol, TypeVar, Callable, dataclass_transform, Any
from dataclasses import dataclass, field

T = TypeVar("T")

class BaseProcessor(Protocol):
    data_source: str # This field will be generated by dataclass_transform

    def process(self, item: Any) -> str:
        """Processes an item, with a default implementation."""
        return f"Default processing of {item} from {self.data_source}"

    def post_process(self, result: str, finalize: bool = False) -> str:
        """Post-processes results."""
        if finalize:
            return result.upper()
        return result

@dataclass_transform(kw_only_default=True)
def processor_factory[T: type](*, enhance_process: bool = False) -> Callable[[T], T]:
    def wrapper(cls: T) -> T:
        if enhance_process:
            # Dynamically replace a method that has a default in the protocol
            original_process = getattr(cls, 'process', None)
            def enhanced_process(self, item: Any) -> str:
                res = original_process(self, item) if original_process else super(cls, self).process(item) # type: ignore
                return f"Enhanced: {res}"
            cls.process = enhanced_process # type: ignore
        return dataclass(frozen=False)(cls)
    return wrapper

@processor_factory(enhance_process=True)
class MyDataProcessor(BaseProcessor):
    data_source: str = "internal-db" # Overrides default init behavior for dataclass
    config_param: int = 10

    # No explicit 'process' method, should get from protocol or enhanced version.
    # No explicit 'post_process' method, should get from protocol.

class AnotherProcessor(BaseProcessor):
    # Not decorated, must implement or rely on defaults + dataclass logic.
    # If not dataclass_transform, `data_source` won't be an __init__ param.
    def __init__(self, data_source: str, config_param: int):
        self.data_source = data_source
        self.config_param = config_param

    def process(self, item: Any) -> str:
        return f"Another processed {item} from {self.data_source} with config {self.config_param}"

if __name__ == "__main__":
    processor1 = MyDataProcessor(config_param=5) # 'data_source' has a default
    print(processor1.process("data_A"))
    print(processor1.post_process("processed_A", finalize=True))
    # reveal_type(processor1.process)
    # reveal_type(processor1.data_source)

    processor2 = AnotherProcessor(data_source="external-api", config_param=20)
    print(processor2.process("data_B"))
    print(processor2.post_process("processed_B"))
    # Type checkers might disagree on:
    # 1. Whether MyDataProcessor correctly implements BaseProcessor (dataclass_transform vs Protocol defaults).
    # 2. The constructor signature of MyDataProcessor.
    # 3. The actual callable used for 'process' (decorated, protocol default, or inherited).